#!/bin/sh

set -eu

ARCH="${ARCH:-$(uname -m)}"
case "$ARCH" in
	amd64) ARCH=x86_64 ;;
	arm64) ARCH=aarch64 ;;
esac

APPIMAGE_ROOT="$(pwd)"
BINARY="https://github.com/xenia-canary/xenia-canary-releases/releases/latest/download/xenia_canary_linux.tar.xz"
BINARY_FALLBACK="https://github.com/xenia-canary/xenia-canary-releases/releases/latest/download/xenia_canary_linux.tar_.xz"
XENIA_SOURCE_URL="${XENIA_SOURCE_URL:-https://github.com/xenia-canary/xenia-canary.git}"
XENIA_CANARY_REF="${XENIA_CANARY_REF:-9478cda5d643f31ce5eddaa3a698282887515439}"
XENIA_BUILD_FROM_SOURCE="${XENIA_BUILD_FROM_SOURCE:-0}"
PATCH_DIR="${PATCH_DIR:-$APPIMAGE_ROOT/patches/xenia-canary-aarch64}"

as_root() {
	if [ "$(id -u)" -eq 0 ]; then
		"$@"
	else
		sudo "$@"
	fi
}

echo "Installing dependencies..."
echo "---------------------------------------------------------------"
if command -v apt-get >/dev/null 2>&1; then
	as_root apt-get update
	as_root env DEBIAN_FRONTEND=noninteractive apt-get -y install \
		alsa-utils \
		build-essential \
		clang \
		cmake \
		git \
		glslang-tools \
		libasound2-dev \
		libasound2-plugins \
		libegl-dev \
		libfontconfig-dev \
		libfreetype-dev \
		libgdk-pixbuf-2.0-0 \
		libgtk-3-0 \
		libgtk-3-dev \
		liblz4-dev \
		libopengl-dev \
		libpipewire-0.3-0 \
		libpulse0 \
		librsvg2-2 \
		libsdl2-dev \
		libvulkan-dev \
		libx11-dev \
		libxcb1-dev \
		libxml2 \
		lld \
		llvm \
		mesa-vulkan-drivers \
		ninja-build \
		pkg-config \
		pipewire-alsa \
		python3 \
		spirv-tools \
		vulkan-tools \
		wget \
		xz-utils \
		zlib1g-dev
elif command -v pacman >/dev/null 2>&1; then
	pacman -Syu --noconfirm \
		alsa-lib          \
		alsa-plugins      \
		base-devel        \
		clang             \
		cmake             \
		git               \
		glslang           \
		gtk3              \
		libx11            \
		libxcb            \
		lld               \
		llvm              \
		lz4               \
		ninja             \
		pkgconf           \
		pipewire          \
		pipewire-alsa     \
		python            \
		sdl2              \
		spirv-tools       \
		vulkan-headers    \
		vulkan-icd-loader \
		wget              \
		xz                \
		zlib

	echo "Installing debloated packages..."
	echo "---------------------------------------------------------------"
	if command -v get-debloated-pkgs >/dev/null 2>&1; then
		get-debloated-pkgs --add-mesa gtk3-mini libxml2-mini opus-mini gdk-pixbuf2-mini librsvg-mini
	else
		pacman -S --noconfirm --needed mesa libxml2 opus gdk-pixbuf2 librsvg
	fi
else
	echo "Unsupported package manager. Need apt-get or pacman." >&2
	exit 1
fi

download_prebuilt() {
	for binary_url in "$BINARY" "$BINARY_FALLBACK"; do
		echo "Downloading '$binary_url'..."
		echo "---------------------------------------------------------------"
		if wget --retry-connrefused --tries=30 "$binary_url" -O /tmp/xenia.tar.xz 2>/tmp/download.log; then
			awk -F'/' '/Location:/{print $(NF-1); exit}' /tmp/download.log > ~/version
			tar xvf /tmp/xenia.tar.xz
			chmod +x ./build/bin/Linux/Release/xenia_canary
			return 0
		fi
		cat /tmp/download.log
	done

	exit 1
}

generate_version_header() {
	header_path="$1"
	ref="$2"
	ref_short="$(printf '%s' "$ref" | cut -c1-9)"

	mkdir -p "$(dirname "$header_path")"
	cat > "$header_path" <<EOF
// Autogenerated by xenia-canary-AppImage.
#ifndef GENERATED_VERSION_H_
#define GENERATED_VERSION_H_
#define XE_BUILD_BRANCH "canary"
#define XE_BUILD_COMMIT "$ref"
#define XE_BUILD_COMMIT_SHORT "$ref_short"
#define XE_BUILD_DATE __DATE__
#define XE_BUILD_PR_NUMBER 0
#endif  // GENERATED_VERSION_H_
EOF
}

build_from_source() {
	echo "Building xenia-canary '$XENIA_CANARY_REF' from source for '$ARCH'..."
	echo "---------------------------------------------------------------"
	rm -rf "$APPIMAGE_ROOT/xenia-source" "$APPIMAGE_ROOT/build"

	git clone "$XENIA_SOURCE_URL" "$APPIMAGE_ROOT/xenia-source"
	cd "$APPIMAGE_ROOT/xenia-source"
	git checkout "$XENIA_CANARY_REF"
	git submodule sync --recursive
	git submodule update --init --recursive --depth=1

	for patch_file in "$PATCH_DIR"/*.patch; do
		[ -e "$patch_file" ] || continue
		echo "Applying $(basename "$patch_file")..."
		git apply "$patch_file"
	done

	export CC="${CC:-clang}"
	export CXX="${CXX:-clang++}"

	cmake -S . -B build -G "Ninja Multi-Config" \
		-DCMAKE_BUILD_TYPE=Release \
		-DXENIA_BUILD_TESTS=OFF \
		-DXENIA_BUILD_MISC=OFF \
		-DXENIA_ENABLE_LTO=OFF
	generate_version_header "$APPIMAGE_ROOT/xenia-source/build/version.h" "$XENIA_CANARY_REF"
	cmake --build build --config Release --target xenia-app --parallel "${XENIA_BUILD_JOBS:-$(nproc)}"

	built_binary="$(find build/bin/Linux -name xenia_canary -type f -perm /111 | head -1)"
	if [ -z "$built_binary" ]; then
		echo "Could not find built xenia_canary binary" >&2
		exit 1
	fi

	mkdir -p "$APPIMAGE_ROOT/build/bin/Linux/Release"
	cp -f "$built_binary" "$APPIMAGE_ROOT/build/bin/Linux/Release/xenia_canary"
	chmod +x "$APPIMAGE_ROOT/build/bin/Linux/Release/xenia_canary"
	printf '%s\n' "$XENIA_CANARY_REF" | cut -c1-7 > ~/version
}

case "$ARCH" in
	x86_64)
		if [ "$XENIA_BUILD_FROM_SOURCE" = "1" ]; then
			build_from_source
		else
			download_prebuilt
		fi
		;;
	aarch64)
		build_from_source
		;;
	*)
		echo "Unsupported architecture: $ARCH" >&2
		exit 1
		;;
esac
